### ISSUE TITLE
Request: Refactor -> Add/Remove braces around arrow function body

### ISSUE THREAD

**Issue by alexilyaev** [cmstead/js-refactor#101]
AKA "**Remove braces around arrow function body**" from JetBrains IDE's:  
https://www.jetbrains.com/help/phpstorm/javascript-braces-around-arrow-function-body-can-be-removed.html

> Reports arrow functions where the body contains exactly one statement and can be converted to concise syntax without braces.
> 
> ```js
> let incrementer = (x) => {return x + 1};
> ```
> 
> Reports arrow functions where the body contains exactly one statement and can be converted to concise syntax without braces.
> 
> ```js
> let incrementer = (x) => x + 1;
> ```

And the reverse with "**Add braces to arrow function**".

### Notes:

1. Should support any body return expression, as long as it's the only one, e.g.:

```js
const Heading = () => {
  return (
    <h1>Something</h1>
  );
};
```

WebStorm result:

```js
const Heading = () =>
  (
    <h1>Something</h1>
  );
```

I would expect this one:

```js
const Heading = () => (
  <h1>Something</h1>
);
```

2. Object return:

```js
const getData = () => {
  return {
    foo: 123
  };
};
```

Expected:

```js
const getData = () => ({
  foo: 123
});
```
---

Was mentioned in https://github.com/cmstead/js-refactor/issues/67 but this one is more specific to arrow functions.

**Comment by cmstead** [comment]
I did a quick and dirty migration of this issue to JS CodeFormer, the replacement for JS Refactor. This is on the short list. Keep an eye out, I'll be adding this soon.

https://github.com/cmstead/js-codeformer/issues/15

**Comment by cmstead** [comment]
This has been moved the JS CodeFormer and is complete. It is available in the latest version:

https://github.com/cmstead/js-codeformer/releases/tag/v1.8.0
