### ISSUE TITLE
Contribute Code Actions along with commands

### ISSUE THREAD

**Issue by mjbvz** [cmstead/js-refactor#102]
Hi, I work on VS Code's code action API and its builtin JS/TS refactorings. It looks like this extension currently uses commands to contribute refactorings. I suggest looking into contributing [code actions](https://github.com/microsoft/vscode-extension-samples/tree/master/code-actions-sample) as well

Code Actions give you a lot for free, such as hooking into VS Code's [built-in refactor UX](https://code.visualstudio.com/docs/editor/refactoring). They also provides users with a most consistent refactoring experience (especially when you start working with multiple extensions that all provide refactorings)

One potential challenge of supporting code action model is that users usually do not request a specific code action or refactoring. Instead VS Code asks extensions which refactorings apply for the given editor state. For example, if the user makes a selection and runs the generic `Refactor...` command in VS Code, your extension would have to determine which refactorings to return. This behavior can help users discover refactorings (and also means they don't see ones that can't be run for the current selection) but it may be challenging to support this depending on how your extension is currently written.

Let me know if you have any questions about code actions in VS Code. I'd also be interested in hearing if there are any blockers that prevent you from moving to code actions. This month for example we are looking into improving code action discoverability and UX with https://github.com/microsoft/vscode/issues/82718

**Comment by cmstead** [comment]
After discovering any extension which hooks into code actions is disabled when the editor is a guest in a Live Share session, I've decided I won't be moving forward on this.  I did build a suggestion system into JS CodeFormer built on the same diagnostics I use to verify whether an action can be done.

You can see what I have here:

https://github.com/cmstead/js-codeformer/tree/v1.12.0
