### ISSUE TITLE
Convert exported function doesn't work

### ISSUE THREAD

**Issue by BigsonLvrocha** [cmstead/js-refactor#106]
```typescript
export function foo() {
  return 'bar';
}
```
won't convert to 
```typescript
export const foo = () => 'bar'
```
nothing happens

**Comment by cmstead** [comment]
Hm. I'll have a look into this.

**Comment by cmstead** [comment]
This was tested with the latest version of JS CodeFormer (I'm sure you saw my other notes, so I won't repeat) and it works properly. Yay!

https://github.com/cmstead/js-codeformer/releases/tag/v0.13.5
