### ISSUE TITLE
Feature request: Invert if

### ISSUE THREAD

**Issue by henrikrudstrom** [cmstead/js-refactor#109]
One of my favorite refactors in Visual Studio was the Invert-if statement refactor: 

```
if(someCondition){
..do a lot of work
}
return;
```

becomes
```
if(!someCondition){
  return
}
...do a lot of work
```

**Comment by cmstead** [comment]
I'll have a look and see what I can do. It seems reasonable to accomplish.

**Comment by cmstead** [comment]
I've moved this to the replacement project. Please see the new issue here. It's on the shortlist for implementation, so you should see it soon.

https://github.com/cmstead/js-codeformer/issues/14

**Comment by cmstead** [comment]
This is complete in the latest release of JS CodeFormer:

https://github.com/cmstead/js-codeformer/releases/tag/v1.2.1
