### ISSUE TITLE
[Documentation / Wiki] Lets create some Before / After examples & Gifs?

### ISSUE THREAD

**Issue by martinandersen3d** [cmstead/js-refactor#113]
I love the initiative of this extension. 

But I'm having a hard time to figure out, how some of them works. I guess other people maybe feel the same.

I suggest we can add to the Readme or create a more detailed wiki ( https://github.com/cmstead/js-refactor/wiki ) 

For learning purpose, I suggest we could use both approaches?:

- Gif's showing how how it works. This will show where to place the cursor / selection and execute.
- Text examples with Before / After

-----------Example-----------------:

![GIF 12-05-2020 21 34 32](https://user-images.githubusercontent.com/19984581/81737468-6e9dda00-9498-11ea-93d2-c52814d83b36.gif)

Before:
```
class ClassName {
    constructor( params ) {

    }

    helloWorld( a, b ) {
        return a+b
    }
}
```

After:
```
class ClassName {
    constructor( params ) {

    }

    add( a, b ) {
        return a + b;
    }

    helloWorld( a, b ) {
        return this.add( a, b )
    }
}
```

Programs for Gif recording:
Windows: GifCam
Mac: recordit.co

**Comment by martinandersen3d** [comment]
inline variable

![inline variable](https://user-images.githubusercontent.com/19984581/81749740-7f584b00-94ac-11ea-93df-e03f247e43c2.gif)

**Comment by cmstead** [comment]
I'll definitely want to get this rolling. I have plans for the next year or so, and that includes creating a larger site dedicated to how the extension works, examples, etc. There's just a lot of work to do before I get there.

I'll keep this thread updated as I go.

**Comment by cmstead** [comment]
I know it took a long time to get here. Nevertheless, I ended up building a replacement package from scratch (which is a drop-in replacement for many of the key features, including keybindings) and this new package has screencasts of the 5 core refactorings in the readme.

I am currently in the process of deciding where I want additional docs to live, but this is a start, at least.

Thank you for suggesting this!

https://marketplace.visualstudio.com/items?itemName=cmstead.js-codeformer
