### ISSUE TITLE
Snippets: insert lambda function

### ISSUE THREAD

**Issue by dibikhin** [cmstead/js-refactor#22]
`=>` should insert `(<cursor1>) => { <cursor2> }`

**Comment by cmstead** [comment]
Totally doable. I also welcome pull requests and this would be a good one to do if you are interested in contributing!

**Comment by dibikhin** [comment]
Nice. Ok, I am! Will try to do this on the weekend.

**Comment by cmstead** [comment]
Sounds good. Let me know if you have questions.

**Comment by dibikhin** [comment]
Ok, tnx.

**Comment by dibikhin** [comment]
Done, created a pull request.

**Comment by cmstead** [comment]
PR merged. Leaving open until I can get this into the next release.

**Comment by dibikhin** [comment]
Nice :)

**Comment by cmstead** [comment]
This should be available in the current release (v0.6.1)
