### ISSUE TITLE
Context Menu Options

### ISSUE THREAD

**Issue by cmstead** [cmstead/js-refactor#23]
Basic idea: Add refactoring options to context menu in editor

I am adding this enhancement because it is, by far, the most requested item and I have no idea how to implement it.  I am currently seeking an answer (if there is one to be had) but if someone has any information to help, it would be greatly appreciated.

If you have any ideas, please investigate and share

**Comment by cmstead** [comment]
After reviewing the extension points document, it appears you cannot extend the context menu (right-click menu). This means we may have to wait until VS Code supports this before this request can be fulfilled.  For now, hopefully namespacing the actions in the command palette will help to ease the cognitive burden of remembering all the refactoring names.

**Comment by cmstead** [comment]
Here's the currently supported extension points for reference:

https://code.visualstudio.com/docs/extensionAPI/extension-points

**Comment by dibikhin** [comment]
Hope, they'll add something. VS Code is evolving fast. It's possible to ask them for that feature.

**Comment by dibikhin** [comment]
It'd be nice if one could hit something like `ctrl+r+r` or `alt+enter` to see all available refactorings or appropriate ones for selected text like ReSharper does.

**Comment by cmstead** [comment]
It has been a while since I last had a chance to look at this. I'll see what VS Code supports now and maybe there will be some movement I can make.

**Comment by cmstead** [comment]
This is complete in version 0.7.0!

https://marketplace.visualstudio.com/items?itemName=cmstead.jsrefactor
