### ISSUE TITLE
Convert To Named Function: should it convert to named function?

### ISSUE THREAD

**Issue by dibikhin** [cmstead/js-refactor#25]
When I select all the code or just the function declaration here:

    ee.on('event', function(params) {
    // do something
    });

And hit `shift+ctrl+j shift+ctrl+n` it only shows me a notification `No appropriate anonymous or member function to convert.` Should it give me lines below?

    function new_handler (params) {
        // do something
    }
    mediator.on('event', new_handler);

I think that `Convert To Named Function` should extract a function from a selected code.

**Comment by cmstead** [comment]
This would really need to be a different behavior. The purpose of convert to named function is to do this :

myfn: function () {} 

To

function myfn () {}

**Comment by dibikhin** [comment]
Ok. Got it. I'll create an issue for that case named `Extract function`.

**Comment by dibikhin** [comment]
May be closed.

**Comment by cmstead** [comment]
Closing.
