### ISSUE TITLE
Lift and name function

### ISSUE THREAD

**Issue by dibikhin** [cmstead/js-refactor#26]
Selecting this or function body only

```
ee.on('event', function(params) {
    // do something
});
```

and firing `convert to named function` should give this:

```
function new_handler (params) {
    // do something
}
mediator.on('event', new_handler);
```

Context: I often start with closures. When they get too complex I start to refactor them by moving to named functions.

**Comment by cmstead** [comment]
I like it.

My only thought is, perhaps we could call this "lift and name function"  instead? Extract function has a very specific meaning in refactoring.

**Comment by dibikhin** [comment]
Sure.

`Extract function` is more like 'take this piece of code and wrap it in function'.

**Comment by cmstead** [comment]
I'm starting to get the code into a real testable state with the use of an IoC container. Real, new features should be forthcoming soon.

**Comment by macta** [comment]
I am wondering if this is the equivalent of extract method from the refactoring world? I can't find extract "method/function/code" in this plugin and its one of the most used refactorings in other languages. Am I missing something - or is this still something to be written (as implied here?)

**Comment by cmstead** [comment]
Hi @macta Extract function is still being worked on as it requires a fair amount of scope management and identification of unbound variables which must be bound to the extracted function. It's definitely on my radar, but I had several pressing issues (which are now resolved) I really had to deal with before I could start addressing whole new functionality.

Regarding this particular request, what needs to actually happen is the function needs to be lifted out of the current context it is in, named and placed at a higher scope.  I'm currently identifying things which need to be considered, like where does the function get hoisted to, is the current scope wrapped in a condition (so the function must be hoisted above that) etc.

Nevertheless, I think my next priority in working toward extract function is actually updating "wrap in executed function" to offer an option to rebind unbound parameters.  That will carry everything to a state where the extract will be little more than deciding on the scope to extract the function to.

I don't know if this is the answer you were looking for, but hopefully it provides some clarity around what my next step is. : )

**Comment by macta** [comment]
Thanks, thats a good answer. So, the direction of the plugin is what I expect, and I appreciate that its a work in progress. It might be worth mentioning that in your market place description to set the right expectation. Thanks for running with this by the way - its great to see some challengers to Eclipse and Jetbrains (which this plugin brings)

**Comment by cmstead** [comment]
@macta I wanted to let you know, extract method is now fully implemented and available in the new version of the plugin.  I have started doing some really heavy work on this plugin again (burnout is totally a thing) and I am currently doing some fast and furious development to knock the issue list down.  The lift and name behavior will likely come in the near future as well. : )

https://marketplace.visualstudio.com/items?itemName=cmstead.jsrefactor

**Comment by cmstead** [comment]
Lift and name function expression is now available in the latest version of JS Refactor.  You can get it here:

https://marketplace.visualstudio.com/items?itemName=cmstead.jsrefactor
