### ISSUE TITLE
Indentation in IIFE

### ISSUE THREAD

**Issue by con-ssc** [cmstead/js-refactor#28]
When you wrap a function that contains an if conditional, the indentation of the if gets messed um.

**Comment by cmstead** [comment]
Thanks for submitting this. It's definitely on the radar and it's not the only place formatting goes wonky. I'll dig into the issue as I get tests around more of the logic.

**Comment by cmstead** [comment]
It has taken forever for me to get back to this, but I have a fix I am introducing in the next version of the tool. I'll update as the release starts to come together.

**Comment by cmstead** [comment]
This should be in the latest release (v0.6.1)
