### ISSUE TITLE
"Negate if" refactoring

### ISSUE THREAD

**Issue by ripper234** [cmstead/js-refactor#31]
This refactoring reduces nesting level, makes flow easier to understand

**Before**

```
function foo() {
  if (cond) {              // <-- Caret is here
    bar()
  }
}
```

**After**

```
function foo() {
  if (!cond) {
    return
  }
  bar();
}
```

**Comment by cmstead** [comment]
Hm, that could be a bit tricky.  I'll look into it.

**Comment by cmstead** [comment]
On second glance, though I understand what you are trying to accomplish here, but I'm a little concerned about this kind of rewriting. It feels like it is centered around a pretty specific use case. What would the expected behavior for this same refactoring be in the following case:

~~~
function foo() {
    if(cond1) {
        bar();
    } else if (cond2) {
        baz();
    } else {
        quux();
    }
}
~~~

It's unclear which part of the conditional would be negated and how the code should be restructured.  There are many paths that could be followed and it's hard to guess the intent the developer had. : (

**Comment by ripper234** [comment]
This is a standard refactoring in refactoring tools in other languages, e.g. Resharper or IntelliJ

In the above use case, the expected output is

```js
function foo() {
    if(!cond1) {
      if (cond2) {
        baz();
      } else {
        quux();
      }
    } else {
      bar();
    }
}
```

See also https://www.refactoring.com/catalog/reverseConditional.html

(A nice resource I just found that contains many potentially useful refactorings we could implement)

**Comment by cmstead** [comment]
I'll play with it in intellij and see how the various cases resolve. Thanks for the info!

**Comment by cmstead** [comment]
I did some research on IntelliJ, Webstorm and Resharper to see how they handle various cases, and it doesn't look like any of them support this refactoring at all. I also couldn't find any documentation on removed historic support.

Perhaps I could reduce the scope on this to negate boolean expression? This would reduce the guesswork I would have to do and give a step toward what you are looking to accomplish.

**Comment by ripper234** [comment]
Again - I meant the refactoring in general (e.g. in C#/Java) is a well known one.
Actually, there are a ton of other refactorings supported by the tools on those languages.

js-refactor would be super useful if it supported some/all of those refactorings that are supported in other similar languages (e.g. extract method/function, extract class, move method, ....). The sky is the limit.

I have no idea about the difficulty of implementing this specific feature, if it's too big of a feature we can break it down / postpone it.

**Comment by cmstead** [comment]
I have created a new issue with the reduced scope to handle condition rewriting cases:

https://github.com/cmstead/js-refactor/issues/32
