### ISSUE TITLE
VS 2017 refactoring and pulling code to functions

### ISSUE THREAD

**Issue by weedkiller** [cmstead/js-refactor#33]
Hi, I have a lot of inplace anonymous functions, and this is great.

I was trying to install into VS 2017 with little success, I was wondering how to pull that code out to named functions, with good practices.

**Comment by cmstead** [comment]
Hi, I haven't looked into it, but I don't think visual studio code extensions work in visual studio. It sounds like you're getting to install this in vs 2017, is that correct?

**Comment by weedkiller** [comment]
yes,  the install templates are very similar in content, just different format, a more generic [older version](https://msdn.microsoft.com/en-us/library/dd885241.aspx) but now they have template project to create the template, hope that helps. Check SIdewaffle
