### ISSUE TITLE
Convert to Lambda

### ISSUE THREAD

**Issue by cmstead** [cmstead/js-refactor#4]
Convert named or anonymous function to fat-arrow lambda notation

    function () {
        // function body
    }

Converts to

    () => { // function body }

**Comment by cmstead** [comment]
I added this a long time ago and nobody has asked about it so I am considering this unnecessary and closing.

**Comment by dibikhin** [comment]
It can be useful while converting a code from ES5 to ES6.

**Comment by cmstead** [comment]
Sure, however, I haven't had anyone specifically ask for it so I'd rather come back around when it becomes a bigger request. Simply swapping everything to lambda expressions might be ill advised. It's not dead forever, just off my radar for the moment. : )

**Comment by dibikhin** [comment]
Exactly :)
