### ISSUE TITLE
Improve necessary selection for variable inline refactoring

### ISSUE THREAD

**Issue by andys8** [cmstead/js-refactor#40]
"Inline a variable" not working.

![vokoscreen-2017-04-22_10-37-14](https://cloud.githubusercontent.com/assets/13085980/25302870/47d4afa4-2748-11e7-9578-4fab07c56c91.gif)

#### Example
1. Select `param`
2. Trigger inline
3. Logs error

```js
function test() {
    var param = 1;
    console.log(param);
}
```

**Comment by cmstead** [comment]
Hi Andy, currently inline variable looks to see if you have selected the variable declaration to inline it. Selecting it elsewhere in the document is not yet supported. I will see if I can figure out a reasonable solution since it will require extra scope management I haven't gotten a chance to work on yet.

**Comment by andys8** [comment]
Okay, it works, if the user is selecting the complete line `var param = 1;`. Would be great to improve it and allow selections of parts or recognize the cursor position, but it's definitely okay if you know how to use it.

Thanks for your clarification, I'll change the title, but you could also close this issue.

**Comment by cmstead** [comment]
No, I won't close it. I think you have a valid use case.

**Comment by cmstead** [comment]
I know this has been sitting for quite a while. I had to do a lot of work to get to the state where I could address this issue. I am actively working on allowing the user to select the variable declaration or use to perform the inline action.

**Comment by cmstead** [comment]
The latest release of JS-Refactorings has a fix for this issue.  You should be able to select any instance of a variable name within the scope local to the variable declaration and inline should work properly.

https://marketplace.visualstudio.com/items?itemName=cmstead.jsrefactor
