### ISSUE TITLE
Add or migrate to const instead of var

### ISSUE THREAD

**Issue by andys8** [cmstead/js-refactor#41]
The refactorings are using `var` when inlining or extracting variables. Would be great to migrate to `const` instead. Another way would be to add `Extract constant` as additional action for the user.

Comparing with IntelliJ idea, they are offering both options:
![image](https://cloud.githubusercontent.com/assets/13085980/25302910/1594db12-2749-11e7-938c-b73ae22dca67.png)
https://www.jetbrains.com/help/idea/2017.1/extract-variable-in-javascript.html

**Comment by cmstead** [comment]
I could definitely add a "convert to constant" and "convert to let." For extract, I could provide options to set the declaration to var, let or const. Would this meet your need?

**Comment by andys8** [comment]
A simple way for the user to directly extract to a `const` would be awesome. I think there are two options: 

There could be a setting to toggle the behavior. But I wouldn't recommend it because it's harder to explain and not easy to understand for new users.

If there would be the exact same behavior "extract to variable" has for "extract to constant" with a different shortcut, it would be a great addition, and it will leave "extract to variable" as it is.

The conversion between `const`, `let` and `var` is a different topic. Probably some users are happy about having this feature but I personally wouldn't use it.

Thanks again for your effort.

**Comment by dericcain** [comment]
Just to toss in another idea, I think it would even be acceptable to just select/highlight the keyword once the refactoring is complete - similar to a snippet. That way, if I wanted to use `var`, I could just hit tab and keep going. But, if I wanted to use `const` or `let`, all I have to do is just type one of those and since the `var` keyword is already selected, it would be really easy.

Just a thought.

**Comment by cmstead** [comment]
Hi! I'm sorry it's taken me so long to work on this, I got caught up in a fix for the atom port. I'll make this my next priority.

**Comment by cmstead** [comment]
Okay, extract variable now supports const, let and var.  My apologies for taking so long to get there, It turned out I had a couple of other creeping bugs in the software that were really high priority.

Version 1.4.0 contains this update!

**Comment by dericcain** [comment]
@cmstead Thanks! This is great news. I really appreciate your hard work on this project.
