### ISSUE TITLE
Convert to JS template literal

### ISSUE THREAD

**Issue by atk** [cmstead/js-refactor#42]
It would be cool to be able to convert stuff like `"test"+i` to ````test${i}```` automatically (markdown swallows the template literal quotes, I hope you know what I mean).

**Comment by cmstead** [comment]
I'll take a look and see what I can do. : )

**Comment by KleoPetroff** [comment]
Any update on this?

**Comment by cmstead** [comment]
Not yet. :-( I'd love help if I can get it!

**Comment by cmstead** [comment]
Okay, this should be available in the latest release, 2.7.0

https://marketplace.visualstudio.com/items?itemName=cmstead.jsrefactor
