### ISSUE TITLE
Convert function expression to arrow function.

### ISSUE THREAD

**Issue by ravshansbox** [cmstead/js-refactor#43]

**Comment by cmstead** [comment]
I'm going to assume this is a conversion task for the following:

```
function (/* arguments */) { /* some body */ }
```

Converts to:

```
(/* arguments */) => { /* some body */ }

**Comment by machineghost** [comment]
It would be great if this refactoring could be  smart enough to also do:

    function (/* arguments */) { return aSingleThingWithNoOtherLogic; }

=>

    (/* arguments */) => aSingleThingWithNoOtherLogic

and:

    function (aSingleArgument) { return aSingleThingWithNoOtherLogic; }

=>

    aSingleArgument => aSingleThingWithNoOtherLogic;

**Comment by cmstead** [comment]
Seems reasonable. I'll see what I can do. I'll start off with a basic conversion and then see where it lands after that. This seems doable, I just don't want to make any bigger promises yet.

**Comment by cmstead** [comment]
A basic version of this has been implemented. I've been caught up with a bunch of stuff the last few weeks, but I wanted to at least get the base behavior implemented.  The expanded functions (counting lines and arguments, then varying the output on that) are still underway.

**Comment by cmstead** [comment]
Okay, since I have the base setup complete for getting arrow function conversions working, I am opening this up if someone would like to help get the conversion intelligence working better.  I will come back around to solve this in time, but I want to make it known I welcome the help!

**Comment by cmstead** [comment]
I have started rewriting this behavior which should support all of the refactoring intelligence requested in the early posts. Expect to see a new release supporting this in short order.

**Comment by cmstead** [comment]
Convert to arrow function has been completely rewritten. Now, if a function is named, it will convert to a named const assigned an arrow function.  If the function is simply a function expression, it will be converted to an arrow function expression.  Multiline functions will be wrapped in a block, single line functions will not.

This update is available in v 2.4.0:

https://marketplace.visualstudio.com/items?itemName=cmstead.jsrefactor

**Comment by bigdoods** [comment]
Hi - Is there any way that I can select all of the functions in a file and run this method on it instead of having to select each function word individually?

Thanks,

**Comment by cmstead** [comment]
Hi @bigdoods,

There is currently no way to do what you're asking for. As we had into the new year, I'll see if I can extract all of the functionality into a CLI tool which might make this kind of bulk refactor easier.

**Comment by zbot473** [comment]
Parameterless functions don't work.

For example: 
```javascript
const listener = server.listen(8080, function() {
  console.log('Your app is listening on port ' + listener.address().port);
})
```
Doesn't become this:
```javascript
const listener = server.listen(8080,() => {
  console.log('Your app is listening on port ' + listener.address().port);
})
```

**Comment by cmstead** [comment]
I have created a new bug for this. Please try to avoid posting bugs on closed feature threads.

#87
