### ISSUE TITLE
Can't extract variable if it is not inside a function

### ISSUE THREAD

**Issue by machineghost** [cmstead/js-refactor#44]
It seems like this extension (perhaps?) doesn't like ES6.  When I tried to extract "`new Foo(SOME_CONSTANT)`" from:

    describe('some test', () => {
      it('does something', async () => {
        const result = await new Foo(SOME_CONSTANT).perform();
        console.log(result);
      });
    });

I got the error "Cannot extract variable if it is not inside a function".  Since the variable I'm trying to extract *is* inside a function, but it's in an arrow function and not a `function` function, it seems like the problem might be that the extension isn't treating arrow functions the same as their older `function` versions.

**Comment by cmstead** [comment]
Yeah, that's entirely possible.  I have also seen this problem just happen in Mocha/Jasmine tests anyway.  I've been meaning to take a look at see what is going on. I switched to using the Babylon parser for handling all of my code analysis, so ES6 should be fully supported, _should_ being the operative word. ; )

Anyway, I'll have a look and see if I can figure out how to resolve this issue.  Thanks for the heads up!

**Comment by cmstead** [comment]
I just finished rewriting a bunch of internals for extract method. In going to use the new tools to overhaul extract method which should fix this problem.

**Comment by cmstead** [comment]
This issue should be fully resolved.  The latest version (v2.0.0) supports extracting variables in any scope and allows the user to select the destination scope. : D
