### ISSUE TITLE
Support extracting multiline values as a variable

### ISSUE THREAD

**Issue by xueeey** [cmstead/js-refactor#45]
This would be great especially for extracting objects

**Comment by cmstead** [comment]
Yeah, that's been on my list.  Thank you for bringing it up here. I'll work on it as I have time. and let you know as things progress. : )

**Comment by cmstead** [comment]
I'm going to be digging deep into this whole behavior, so I should have a resolution for this upcoming.

**Comment by cmstead** [comment]
I just pushed an update which supports extracting any multiline value as long as it is a valid expression. This is available in v2.0.0. : D
