### ISSUE TITLE
Move refactorings into lightbulb?

### ISSUE THREAD

**Issue by KillyMXI** [cmstead/js-refactor#47]
Is it possible to move refactorings into lightbulb instead of shoving everything into context menu?

**Comment by cmstead** [comment]
Not that I'm aware of at the moment. The context menu was requested some time ago and the light bulb is new, which means it may or may not have an api. I'd  welcome any research you might be willing to do.

**Comment by KillyMXI** [comment]
It looks like lightbulb is currently usable only for linter-like extensions that can provide suggestions for changes. And built-in refactorings do not provide suggestions but shown when appropriate entity is selected.

I see no documentation on code actions, so here there are few usage examples:
[vscode-extension-tutorial](https://github.com/hoovercj/vscode-extension-tutorial), [vscode-haskell-linter](https://github.com/hoovercj/vscode-haskell-linter/blob/master/src/features/hlintProvider.ts), [vscode-hlint](https://github.com/lunaryorn/vscode-hlint/blob/master/src/extension.ts), [vscode-spell-checker](https://github.com/Jason-Rev/vscode-spell-checker/blob/2737cfba04e29a85005815144a2058501075ea98/server/src/codeActions.ts)

[refactorProvider](https://github.com/Microsoft/vscode/blob/be88547c66faa61898a66b97097345ae30fe3d61/extensions/typescript/src/features/refactorProvider.ts) inside vscode is the part of host language implementation as it seems, so it's probably not something possible to implement in separate extension. But maybe there are some clues about code actions and lightbulb usage.


I mostly bothered by two issues:
* it's unclear now where refactorings can be applied and how to apply them correctly;
* UI is cluttered all the time with stuff that can be applied only in certain places.

These can be addressed somehow even if it's not possible to do it 100% in the desired way.
So if code actions in their current implementation are of no use, then I'd like to see following:
* refactorings not shown in menu for files other than js;
* user settings parameter to disable them completely if needed;
* explore other ways to show that some refactorings can be applied on current selection/location (hovers?)

**Comment by cmstead** [comment]
I'll see what I can do regarding showing and hiding options around possible behaviors. I can understand your concern about the clutter.

Thanks for the feedback and digging in deeper. I appreciate the effort.

**Comment by cmstead** [comment]
The refactorings in the context menu, limited to JS files only, should only appear when a selection is made (except inline which does not require a selection).  Given the way items are added to the context menu it may not be possible to refine the behavior more, but I will continue to explore. I'll add notes as solutions present themselves.

**Comment by KillyMXI** [comment]
One another approach would be what Git Lens does - put feature buttons into hover pop-up.
Ideally, it would also be combined with refactoring preview.

**Comment by cmstead** [comment]
This kind of extensive modification to the active editor built in behavior will probably take quite some time to sort out and implement.  I appreciate the feedback and I will continue to consider it while I work through enhancing the refactoring tool.

I also accept pull requests,

**Comment by cmstead** [comment]
Okay, I have started working on sketching out some up-front analysis of code to provide information on refactorings which could be applied.  There is currently a keybinding to pull up the list of available options. I am looking at starting off by filtering that list based on what selection is made and where in the document the selection is. I am going to research if I can dynamically select the options available in the context menu as well.

I don't know that I will be able to provide a preview of the refactoring since several of them require input from the user before I can render anything, and some of the actions (like extract method) are actually pretty expensive and can take up to 1 full second to process and render, which means the preview could be pretty slow.

**Comment by cmstead** [comment]
It's been quite a while since this was opened.  There are many restrictions around what can be shown in the context menu and the light bulb. Perhaps I'll be able to pursue this further later, but for now I think I am going to have to close the issue.
