### ISSUE TITLE
Install silently fails on Mac OS

### ISSUE THREAD

**Issue by MichaelPaulukonis** [cmstead/js-refactor#48]
The install appears to work, but after reload the commands cannot be found from keybindings.

I attempted to manually install all packages via `npm i` but that fails on `edge@7.10.1`

I've commented on [an existing issue for Edge](https://github.com/tjanczuk/edge/issues/593#issuecomment-353608203) about the problem (including some potential workarounds that didn't).

This appears to be an issue with Edge or an Edge dependency.

**Comment by cmstead** [comment]
Oh wow. I'll look at the packages and see where the dependency on edge is hiding. I don't use it explicitly, so if I can break the dependency I will. I'm sorry for the inconvenience. Thanks for the heads up.

**Comment by cmstead** [comment]
I took a look and it appears edge is only required in the dev dependencies (approvals). It seems odd that VS Code would install the dev dependencies, but that could be happening.

I'm going to dig into the package that uses edge and see why they need it. Maybe this can help make things better for them (and us).

**Comment by cmstead** [comment]
If you could do me a favor and try running `npm i --production` and see if the install runs okay? Please let me know if you see any errors.

**Comment by cmstead** [comment]
Okay, in the interim, I created a fork of approvals and pulled the reference to edge. It isn't necessary for running or developing this project. Version 2.10.4 may install better on your machine. Please let me know if this resolves your issue. I'll test everything out on my mac this evening when I get home.

**Comment by cmstead** [comment]
I tested the install on my Mac and everything worked fine.  It appears the issue is that the ctrl/cmd difference isn't being picked up and all hotkeys require the control key, not the command key.  I am going to consider the installation issue closed and create a new issue related to this one for fixing the hotkey combination issue.

**Comment by cmstead** [comment]
Hotkey issues should be fully resolved:

https://marketplace.visualstudio.com/items?itemName=cmstead.jsrefactor

Be sure to note the keybinding updates from older versions:

- Menu of available refactorings - cmd+shift+j r
- Extract method - cmd+shift+j m
- Extract variable - cmd+shift+j v
- Inline variable - cmd+shift+j i
- Rename variable (VS Code internal) - F2
- Convert to Arrow Function - cmd+shift+j a
- Convert to Template Literal - cmd+shift+j l
- Export function - cmd+shift+j x
- Shift parameters - cmd+shift+j s
- Wrap selection - cmd+shift+j w
