### ISSUE TITLE
Refactorings unavailable for .jsx files?

### ISSUE THREAD

**Issue by ehahn9** [cmstead/js-refactor#50]
Probably my newbie-ness, but I've noticed that no refactorings seem to be available for .jsx files? If I rename the file to .js, then the refactoring commands appear.

Might it be possible to add .jsx as a compatible file type?

**Comment by cmstead** [comment]
Ah, I'll have a look. I think this should be a pretty quick fix. Sorry for the delay.

**Comment by ehahn9** [comment]
wonderful! happy to try it out.

**Comment by cmstead** [comment]
It should be all set in v2.11.4:

https://marketplace.visualstudio.com/items?itemName=cmstead.jsrefactor

Thanks for letting me know!
