### ISSUE TITLE
Support for .vue single file component

### ISSUE THREAD

**Issue by asifm** [cmstead/js-refactor#51]
Currently, the extension doesn't work on the JavaScript within the <script> tag of a [single file vue component](https://vuejs.org/v2/guide/single-file-components.html). These files have .vue extension.

Is there a way to make the extension work with these files?

**Comment by cmstead** [comment]
Hi, I can look into it and see what I can do. Currently I am parsing everything with Esprima with the JSX plugin turned on. There isn't really a vue plugin or extension, but I'll see if I can reasonably extract the Javascript and work with it directly, then replace it. I'll update as things progress.

**Comment by asifm** [comment]
That'll be really helpful if it can be done.
I don't know if these are going to help, but it seems so —
https://www.npmjs.com/package/vue-parser
Also, https://stackoverflow.com/questions/47785382/convert-single-file-vue-components-to-javascript, which references https://www.npmjs.com/package/vue-template-compiler

**Comment by cmstead** [comment]
I'll have a look at these projects. I have pretty specific needs to integrate with VS Code, so no promises just yet. Also, I know this has been sitting for a month, I promise I've been thinking about a solution. :'(

**Comment by cmstead** [comment]
I am looking at supporting Javascript embedded in languages using XML style markup which encloses the code.  This should also encompass the need presented with Vue single-file component files.  I will test the case presented in this issue as well, but feel free to watch the associated issue: #63

**Comment by JSN190** [comment]
Apologies for digging up this issue, but have there been any updates in regards to progress on this issue?

**Comment by cmstead** [comment]
No worries and, yes! There has been some movement. I got the refactorings working in HTML, so now that I have a bug in my ear, I can look into getting the configuration right. Thanks for pinging me on this!

**Comment by JSN190** [comment]
That's great news. Best of luck!

**Comment by cmstead** [comment]
I just pushed an update to include .vue files as Javascript source.  This is effectively an alpha release, so I'd really like people to provide feedback if something acts weird.

Known issue: if you don't have a formatter set up for Vue single file components, VSCode will try to format your code and it will get weird. I don't know that I can do much about this at the moment.

**Comment by cmstead** [comment]
I haven't heard anything one way or another, so I am hopeful that the update worked for people. If anything bubbles up, please submit an issue and I'll dig in.

**Comment by webcoderkz** [comment]
it doesn't work with Vue & TypeScript & Class styled components: https://github.com/cmstead/js-refactor/issues/100
