### ISSUE TITLE
Keyboard shortcuts aren't working

### ISSUE THREAD

**Issue by Dreykodoon** [cmstead/js-refactor#52]
As an example, when I try to extract a variable and press _ctrl+shift+j v_, I get the following warning:

> WARN: command 'cmstead.jsRefactor.extractVariable' not found

This goes for other keyboard shortcuts as well, such as extracting methods.

I am using the following:
vscode: version 1.19.2
JS Refactor: version 2.11.4

**Comment by cmstead** [comment]
Interesting, I've seen this a couple times before. Most of the time, what I have found is there is something that is "non-standard" Javascript in place.  Things which can cause this that I have seen (and cannot repair at the moment, though I'm working on a plan) are as follows:

Javascript with a shebang at the top: `#!/usr/bin/env node`
Javascript with flow annotations
Typescript code in a JS file
Vue single-file components
ES Next features currently in early-phase progress (phase 1 or 2 development)

Do any of these fit your current situation?

**Comment by cmstead** [comment]
Since I haven't seen a response yet, I am going to assume this is resolved?  Please let me know if you are still having issues or if one of the above scenarios was the culprit.  Thanks.
