### ISSUE TITLE
TypeScript support?

### ISSUE THREAD

**Issue by alex-weej** [cmstead/js-refactor#54]
This extension looks perfect for some cleanups I've been planning, but I can't use it on my project because it's TypeScript. Long shot, but is there any chance this can somehow be made to work with TypeScript files?

Thanks

**Comment by cmstead** [comment]
I would like to and I started exploring it at one point, but right now the hurdle I have to overcome is pretty high.  It's still  on the radar, so please understand this isn't a no, simply a "I don't have a good solution yet."

**Comment by aaronmcadam** [comment]
Hey @cmstead, are you using TypeScript in your everyday workflow? If not, I could probably help you out. Thanks for being an awesome of an open source maintainer👏👏👏

**Comment by cmstead** [comment]
I'm not using Typescript in my every day. Do you have experience working with the Typescript AST output because that would be awesome. I struggle because Esprima provides such a nice output is hard to convert to something I cant seem to get line and character numbers from or worse (Babel) that doesn't support clean traversal.

**Comment by aaronmcadam** [comment]
I've got experience of jscodeshift, is Esprima on that level of abstraction?

**Comment by cmstead** [comment]
No, Esprima is kind of a no-frills parser, but the AST it provides is really nice. I have bunch of little tools I've built to identify and extract the code I want to transform.

**Comment by cmstead** [comment]
Yeah, I dug into using the Typescript compiler output, but the problem I kept running into was I had no way to correlate the AST nodes to the actual document without counting characters which seemed awfully painful and potentially buggy.

**Comment by aaronmcadam** [comment]
Ahh I understand the problem now! We should connect and talk about this properly, but I think I get the difference now that the vscode team can offer refactorings like reordering or appending to imports - they aren't mutating the actual code, symbols or lexical context, except for renaming.

Thanks for taking the time to explain @cmstead!

**Comment by aaronmcadam** [comment]
Another idea I've just though of is sourcemaps, but I'm not sure if they'd help you with character positions either 😕

**Comment by cmstead** [comment]
Just a quick update, the Typescript conversion has been a priority item for a while. It's just quite an undertaking.  I've not forgotten you!

**Comment by sollyucko** [comment]
Could https://github.com/typescript-eslint/typescript-eslint somehow be used to parse TypeScript instead of Espree to parse TypeScript, as it is designed to produce a compatible AST?

**Comment by sollyucko** [comment]
More specifically, https://github.com/typescript-eslint/typescript-eslint/tree/master/packages/parser.

**Comment by cmstead** [comment]
That's a good find. I'll check it out. Thank you!

**Comment by cmstead** [comment]
Okay, this has been sitting for a long time, mostly because of hand-wringing, but TypeScript support is in! (It's still somewhat experimental and massaging needs to be done, but it's in!)

Thanks to everyone for their patience and support as I worked and fretted about it.

**Comment by alex-weej** [comment]
good job, thanks!

**Comment by cmstead** [comment]
Sure thing. I'm sorry it took so long to get here.
