### ISSUE TITLE
semicolon is always added causing errors when converting to arrow functions

### ISSUE THREAD

**Issue by Silverium** [cmstead/js-refactor#55]
Semicolon is not always needed, and usually it's wrong.
example:
`let whatever;
new Promise(function (resolve, reject) {
  if (whatever) return reject();
  resolve(42);
}).then(console.log)`

When using the refactor:
`new Promise((resolve, reject) => {
  if (whatever) return reject();
  resolve(42);
};).then(console.log)`

As you can see, this is an error for all the linters. It's worse if the semicolon already existed, because it will add an additional semicolon like so: `;;`

**Comment by cmstead** [comment]
I've been encountering things like this as well in my own use.  Thanks for the reminder to get back in there and patch this up.

**Comment by cmstead** [comment]
I'm publishing a new version right now with a fix for this issue. Thanks again for giving me a bump so I remembered to fix this.

**Comment by Silverium** [comment]
Great! Thanks <3
