### ISSUE TITLE
commands not found

### ISSUE THREAD

**Issue by FWBob** [cmstead/js-refactor#56]
I'm having the same issue as #52. Specifically, I've tried Rename and Shift Parameters.

From the context menu, selecting either of the commands fails silently. From the command palette, I get "command 'cmstead.jsRefactor.shiftParams' not found", for example.

I don't believe I have any of the non-standard JavaScript cases you list in #52. Here's an example of code that exhibits the issue:

```javascript
function doSomething(a, b, c) {
    console.log(a, b, c);
}

doSomething(1, 2, 3);
```

I can't rename 'doSomething' or reorder its parameters.

I'm using VSCode 1.20.0 and js-refactor 2.11.4, with the following extensions installed:

DavidAnson.vscode-markdownlint
PeterJausovec.vscode-docker
cmstead.jsrefactor
dbaeumer.vscode-eslint
eamodio.gitlens
maty.vscode-mocha-sidebar
mikestead.dotenv
ms-python.python
streetsidesoftware.code-spell-checker
wayou.vscode-todo-highlight
yzhang.markdown-all-in-one

**Comment by cmstead** [comment]
I just tried your example and had no issues. Is the sample code the only code in the file you are seeing the failure in?

**Comment by FWBob** [comment]
That's the only code in the file.

FYI, I experienced the issue running VSCode in Ubuntu 16.04 LTS, even after I disabled other extensions and deleted all of my settings. I tried it in Windows 8.1 and the above commands worked fine.

**Comment by cmstead** [comment]
Ah! That's a really useful piece of information. I have a hunch I'll explore and get back to you.  Thanks for getting back to me so quickly.

**Comment by cmstead** [comment]
I just had another thought: Do some of the commands work while others don't or is it a problem across the board? I'm wondering because I have tested the plugin extensively in Windows and Mac environments, but not in Linux, so I have really limited insight at the moment.

**Comment by FWBob** [comment]
No problem. I really want to use this extension!

I recall trying a few other commands -- none of them worked, but I didn't try all of them. Every one had the same "command 'XXXX' not found" error message. I can check the others tomorrow when I'm back at my work computer.

**Comment by cmstead** [comment]
That should be enough info. I just wanted to verify the failures.  I'll see what I can do about getting a test environment running for Linux and figure out what is going wrong. Thanks for your patience!

**Comment by FWBob** [comment]
No worries. Thanks for looking into it!

**Comment by tleh** [comment]
i ran into the same issue.
i'm also on Ubuntu 16.04 and VSCode 1.20.0

every command i want to execute gives me a notification like this: "command 'cmstead.jsRefactor.extractVariable' not found"

via context menu nothing happens and no error notifaction is shown

**Comment by FWBob** [comment]
Here are the error messages I get in the developer tools console. I bolded the key lines. These errors occur the first time I attempted to execute a command from the context menu. Subsequent invocation attempts don't appear to generate any more error messages.

> **console.ts:123 [Extension Host] Activating extension `cmstead.jsrefactor` failed: {1}.**
t.log @ console.ts:123
t._logExtensionHostMessage @ extensionHost.ts:394
(anonymous) @ extensionHost.ts:211
emitTwo @ events.js:106
emit @ events.js:194
process.nextTick @ internal/child_process.js:766
_combinedTickCallback @ internal/process/next_tick.js:73
_tickCallback @ internal/process/next_tick.js:104
**console.ts:123 [Extension Host] Activating extension `cmstead.jsrefactor` failed:  undefined**
t.log @ console.ts:123
t._logExtensionHostMessage @ extensionHost.ts:394
(anonymous) @ extensionHost.ts:211
emitTwo @ events.js:106
emit @ events.js:194
process.nextTick @ internal/child_process.js:766
_combinedTickCallback @ internal/process/next_tick.js:73
_tickCallback @ internal/process/next_tick.js:104
**console.ts:123 [Extension Host] Here is the error stack:  Error: Module "vsCodeFactory" does not exist**
	at InjectorError (/home/bob/.vscode/extensions/cmstead.jsrefactor-2.11.5/node_modules/dject/bin/injectorError.js:14:32)
	at throwOnNoModule (/home/bob/.vscode/extensions/cmstead.jsrefactor-2.11.5/node_modules/dject/index.js:195:23)
	at getModuleOrThrow (/home/bob/.vscode/extensions/cmstead.jsrefactor-2.11.5/node_modules/dject/index.js:154:20)
	at Object.build (/home/bob/.vscode/extensions/cmstead.jsrefactor-2.11.5/node_modules/dject/index.js:116:29)
	at activate (/home/bob/.vscode/extensions/cmstead.jsrefactor-2.11.5/extension.js:3:25)
	at Function.t._callActivateOptional (/usr/share/code/resources/app/out/vs/workbench/node/extensionHostProcess.js:688:725)
	at Function.t._callActivate (/usr/share/code/resources/app/out/vs/workbench/node/extensionHostProcess.js:688:409)
	at /usr/share/code/resources/app/out/vs/workbench/node/extensionHostProcess.js:687:572
	at Object.g [as _notify] (/usr/share/code/resources/app/out/vs/workbench/node/extensionHostProcess.js:68:868)
	at Object.enter (/usr/share/code/resources/app/out/vs/workbench/node/extensionHostProcess.js:72:153)
**extensionService.ts:787 Activating extension `cmstead.jsrefactor` failed: {1}.**
R._logMessageInConsole @ extensionService.ts:787
R._logOrShowMessage @ extensionService.ts:801
e.$localShowMessage @ mainThreadExtensionService.ts:32
e._doInvokeHandler @ rpcProtocol.ts:174
e._invokeHandler @ rpcProtocol.ts:159
e._receiveRequest @ rpcProtocol.ts:108
e._receiveOneMessage @ rpcProtocol.ts:90
(anonymous) @ rpcProtocol.ts:33
(anonymous) @ rpcProtocol.ts:213
e.fire @ event.ts:142
(anonymous) @ ipc.net.ts:81
emitOne @ events.js:96
emit @ events.js:191
readableAddChunk @ _stream_readable.js:178
Readable.push @ _stream_readable.js:136
onread @ net.js:560

**Comment by cmstead** [comment]
I'm getting a test and development environment set up to dig into this more. Thanks for all the info!

**Comment by cmstead** [comment]
Okay! I'm setting up a development environment on my brand new Ubuntu 16.04 partition. Let's see if we can get this extension working, shall we? : D

**Comment by cmstead** [comment]
The error has been found and mitigated. There was a capitalization error which caused a package loader issue. I'm surprised, Mac OS X totally blows by this.  Anyway, I pushed the update so you should be able to install the latest version shortly. : )

**Comment by FWBob** [comment]
Looks good on my system. Thanks a lot for getting this fixed, I'm looking forward to using this extension!
