### ISSUE TITLE
Clobbers the whole file on any change

### ISSUE THREAD

**Issue by AndrewRayCode** [cmstead/js-refactor#58]
I managed to get one feature to work:

```
const someThing = new ExtractTextPlugin('thing.scss');
```

I highlight the string, and press `cmd+shift+j v`, it asks me for a confusing first input which I leave blank, then the name, and after creating the variable, it incorrectly reindents the entire file.

**Comment by cmstead** [comment]
Hi Andrew, sorry for the confusion. I'll try to make the first input clearer. It's a selection for which scope your variable goes in, which could be a single option or several depending on how functions and objects are nested.

As far as indenting the file, currently, after any action, JS Refactor uses the built-in VS Code Javascript formatter. Is there a different formatter you are using? I could explore a setting to let users pick the formatter they prefer.

**Comment by cmstead** [comment]
Though I understand the place where this bug report comes from, I don't have enough feedback to make a meaningful move on it, so I am closing this as abandoned.
