### ISSUE TITLE
Support for setting X Tab Space ?

### ISSUE THREAD

**Issue by Paskalouis** [cmstead/js-refactor#60]
Hi,

Just want to ask if there any setting for auto refactor to x tabs space?

Because from what I see, the refactor does automatically set the tabbing to 2 spaces.

Thank you.

**Comment by cmstead** [comment]
Hi, this is actually not set within the refactoring tool, but rather VSCode itself.  The user settings have a place where you can define the number and kind of spaces for indentation.  You can also look into using EditorConfig (http://editorconfig.org/) to manage this as well.  

You can test your formatting settings in VSCode by using the built-in format function (alt+shift+f) and adjust as you need.  Thanks for using the plugin!
