### ISSUE TITLE
FR: Work with unsaved buffers

### ISSUE THREAD

**Issue by myfairsyer** [cmstead/js-refactor#64]
Thanks for your great work!

The refactoring are only available in context menu and command palette after saving my buffer (in that already is in javascript language mode) to a file.

I'd love to be able to use the refacorings in unsaved buffers aswell.

Thanks for considering.

**Comment by myfairsyer** [comment]
See https://github.com/Microsoft/vscode/issues/26873 and https://github.com/cmstead/js-refactor/blob/a22794ddba0726a176cd0c98e8b46c920d3c6ca6/package.json

**Comment by cmstead** [comment]
I'm not going to close this until the publish is complete. Github is a little aggressive with automatically closing stuff.  Thanks again for the help!

**Comment by cmstead** [comment]
Sorry for the long wait, there were some problems with the marketplace publication library. Everything should be up now.  Thanks!
