### ISSUE TITLE
Add/Remove Curly Brackets

### ISSUE THREAD

**Issue by mfulton26** [cmstead/js-refactor#67]
It would be slick to have a refactor command to add or remove curly braces to arrow functions, if statements, for/while loops, switch cases, etc.

**Comment by damiangreen** [comment]
Try installing Prettier. It does this for you automatically.

**Comment by cmstead** [comment]
I've considered allowing people to specify an external formatter, would this be at all interesting regarding the small conversation that happened here?

**Comment by cmstead** [comment]
I'm going to create a new enhancement issue for supporting external formatters. Closing this issue.
