### ISSUE TITLE
Commands Not Working

### ISSUE THREAD

**Issue by wesbos** [cmstead/js-refactor#69]
Hello - trying to use this on VS Code Stable and none of the commands seem to work.

1. make a file called test.js
2.  type this into it:

```js
function hi() {
  console.log('hi');
}
```

3. save it
4. Put my cursor on the first line and run "Convert to arrow function"
5. Get `command:'cmstead.jsRefactor.convertToArrowFunction' failed.`

Any Insights to what I'm doing wrong? I tried re-installing, but that didn't help. 

I'm on VS Code Version 1.23.1 (1.23.1)
Mac OSX Sierra

**Comment by mvolkmann** [comment]
I'm seeing the same thing. I can't get any of the refactorings to work. I'm sure I have the extension installed because most of the snippets do work.

**Comment by mvolkmann** [comment]
I think I may have stumbled across the issue. I had code like this and I wanted to convert the add function to an arrow function.

```js
function add(a, b) {
  return a + b;
}

app.get('/pid', (req: express$Request, res: express$Response) =>
  res.send(String(process.pid))
);
```
When I removed the Flow types from that function signature, the refactor of the add function worked! Is it possible that most of the refactorings fail when Flow types are present because if fails to parse the code?

**Comment by wesbos** [comment]
I've tried it without Flow typings and it still doesnt work :(

**Comment by mvolkmann** [comment]
@wesbos Does it work if you create a file with exactly the content I have above and remove the Flow types?

**Comment by OurChad** [comment]
Same issue for me. Fresh install of VS Code. I'm not using Flow typings. I tried to exact code above but still receive the `command:'cmstead.jsRefactor.convertToArrowFunction' failed.`

VS Code 1.23.1
Windows 10

And just incase another plugin might be causing an issue. VS Code Plugins:

- Auto Rename Tag
- Better Comments
- Bracket Pair Colorizer
- Color Highlights
- ES7 React/Redux/React-Native/JS snippets
- ESLint
- GitLens
- JS Refactor
- JSON5 syntax
- npm Intellisense
- Polacode

**Comment by cmstead** [comment]
Hi, sorry for the long delay.  I'll have a look at this as time permits.  It's been a tough couple of months, but I will definitely make time to check this situation out.  Thanks for all of your patience!

**Comment by wesbos** [comment]
😘Thank you and please don't put this ahead of anything else important :)

**Comment by OurChad** [comment]
Thanks @cmstead. As an update, I've updated to VS Code 1.24, and I tried disabling all other plugins and running the commands again, but still no joy. The only command that seems to work for me at the moment is the wrap selection. All other commands have the same error as above.

**Comment by alienalien13** [comment]
`Running the contributed command:'cmstead.jsRefactor.convertToTemplateLiteral' failed.`
Same issue.
Sorry for pressing, but I guess it's pretty important one, cuz the whole tool doesn't work at all 🙂 
And it is very sad, because the tool supposed to be very cool, I'm pretty excited to use it 😄

**Comment by cmstead** [comment]
There is an update which fixes the function expression -> lambda expression refactoring available for download.  I am still waiting on details regarding the convert to template literal. Are there any other commands that don't work as stated in the documents?

I want to ensure I get everything rounded up before calling this bug complete.  Thanks to everyone who has provided info on misbehaving commands!

**Comment by cmstead** [comment]
Hey all, I haven't seen a response to the last comment in a while, so I am going to go ahead and close this issue.  If something pops up, please open an issue and I'll check it out.

**Comment by alienalien13** [comment]
@cmstead sorry for not responding. Have tried it today - seems it works fine. Thanks for maintaining!

**Comment by cmstead** [comment]
@alienalien13 thanks for the feedback!

**Comment by icorbrey** [comment]
Getting this same issue on v2.20.6, `Running the contributed command: 'cmstead.jsRefactor.convertToArrowFunction' failed.`

**Comment by carlos-menezes** [comment]
Same issue on v2.20.6 on VS Code 1.57.1.

**Comment by tomvonclef** [comment]
Same issue on v2.20.6 on VS Code 1.58.2
Tried it on
```js
function select(id) {
  window.jape.userChange(id);
}
```

![image](https://user-images.githubusercontent.com/784653/125950407-ae6bbd36-739a-4593-a034-60049dca7248.png)
![image](https://user-images.githubusercontent.com/784653/125950284-a35f3002-e989-479e-8403-a7d507439233.png)
