### ISSUE TITLE
Addition: Mark Function as async

### ISSUE THREAD

**Issue by wesbos** [cmstead/js-refactor#70]
Aside from my other issue, is there a workflow we could add that would mark a function as async? 

So often I'm in a function and need to await inside of it. This has me going up a few lines to the function definition and adding the `async` keyword. Would love if there was a workflow for this

**Comment by mvolkmann** [comment]
I'm seeing the same thing. I can't get any of the refactorings to work. I'm sure I have the extension installed because most of the snippets do work.

**Comment by cmstead** [comment]
That seems like something that shouldn't be too bad. I'll address the defects first, then come back around.

**Comment by cmstead** [comment]
Sorry for the super long lag. This should have been a quick update.  I'm starting to get a little time back to handle stuff, so you should see this come in short order.

**Comment by cmstead** [comment]
I'm at a spot where I can dig into this. Assigning myself and getting this added in.

**Comment by cmstead** [comment]
This is all set and ready to go:

https://github.com/cmstead/js-refactor/releases/tag/v2.17.1
