### ISSUE TITLE
Addition: function declaration

### ISSUE THREAD

**Issue by aaronmcadam** [cmstead/js-refactor#71]
The function expression refactoring works really nicely, but I'm wondering if there's a way to improve the workflow involved in converting from a function expression to a function declaration. 

Here's a screencap that explains what I mean:

![function-declaration-refactoring](https://user-images.githubusercontent.com/37928/40784258-0bea8116-64dd-11e8-9638-48e08de1ef84.gif)

**Comment by aaronmcadam** [comment]
Hey! Thanks for getting back to me, I understand you're busy! Is there any way I could help? Are you using codemods to implement this? If so I've got a little bit of experience of that.

Either way, thanks for an amazing plugin 😍♥️

**Comment by cmstead** [comment]
I haven't used codemods. This is basically all organic, farm to table artisan code. ;-) I'll have to check codemods out andsee if it can simplify things.

Anyway, I'm always open to help if someone has the time!

**Comment by aaronmcadam** [comment]
I think it'd be helpful to see a simplified overview of how the refactorings are implemented, if you have the time. Otherwise I'll have a dig into the code next week 👍

**Comment by aaronmcadam** [comment]
As a side note @cmstead, would it be a lot of effort to hook into vscode's code action API? Have you had time to reach out to their development team at all? I appreciate the effort involved in doing that though!

**Comment by cmstead** [comment]
I'm going through and assigning myself to things I want to solve ASAP. Expect to see movement on this soonish.

**Comment by cmstead** [comment]
Alrighty, this is next up. Thanks for your patience!

**Comment by cmstead** [comment]
This should be all set to go.  The latest release just got published to the marketplace, but in the meanwhile, here's the VSIX file for side-loading:

https://github.com/cmstead/js-refactor/releases/tag/v2.18.0

**Comment by cmstead** [comment]
There was a bug in the previous release. Sorry about that:

https://github.com/cmstead/js-refactor/releases/tag/v2.18.1
