### ISSUE TITLE
Request: Refactor -> Reorder Functions

### ISSUE THREAD

**Issue by nyteshade** [cmstead/js-refactor#73]
It would be fantastic to have a refactor option to 

- reorder the class functions by (name and by accessor such as static or get or set)
- reorder the class properties by name and get/set status

Many Java IDEs support this but you'll need to use some JavaScript AST parsers to get this right in JS.

**Comment by aaronmcadam** [comment]
Could might be a way to implement this using TypeScript's support for these sort of AST manipulations.

Setting the `target` to `esnext` should be good enough?

**Comment by cmstead** [comment]
I should be able to order functions, but I might need a code example to better understand what the input and output would look like.

**Comment by cmstead** [comment]
This issue has been open for more than 6 months without the clarification I need to move forward. Please feel free to respond to this message if you are able to provide an example of code input and output, and would like me to pursue this further.
