### ISSUE TITLE
"Shift parameters" does not shift actual parameters

### ISSUE THREAD

**Issue by thoni56** [cmstead/js-refactor#74]
I don't know if this is particular to my environment, but "Shift parameters" only shifts the formal parameters, not the actual argument expressions (in the calls).

This is not a refactoring unless it does both.

**Comment by cmstead** [comment]
This has been sitting for a while and I wanted to at least come back and touch on it. I will take a look and see if I can effectively select functions to reorder their arguments.  When this was created, it was actually a request just for the formal parameters.  Nevertheless, I will see if I can affect the functions within the local source.  Currently reaching outside of the current file is tricky to accomplish in Javascript.

**Comment by cmstead** [comment]
Updated and marked as an "action" rather than a refactoring. I also removed it from the primary drop-down menu. I'm going to close this for the time being.
