### ISSUE TITLE
convert to lambda bugs

### ISSUE THREAD

**Issue by Spongman** [cmstead/js-refactor#76]
1) it fails to remove the trailing semicolon in a single-statement function. ie.
```javascript
  var f = (function() {
    return foo;
  });
```

is converted to

```javascript
  var f = (() => foo;);
```

which is an error.

2. when the function has a single parameter, the parenthes should be removed:

```javascript
  var f = (function(a) {
    return a;
  });
```

is converted to
```javascript
  var f = ((a) => a);
```

it should be:
```javascript
  var f = (a => a);
```

**Comment by cmstead** [comment]
Thanks for the heads up. I'll write a test around it and get this fixed.

**Comment by Spongman** [comment]
here's another:

3. braces should _not_ be removed when single-statement function body is a control statement.

```javascript
  var f = (function(a) {
    if (true) a = 0;
  });
```

is converted to

```javascript
  var f = ((a) =>
    if (true) a = 0);
```

which is an error (also badly indented).

should be:
```javascript
  var f = ((a) => {
    if (true) a = 0
  });
```

**Comment by cmstead** [comment]
Awesome. Thanks for reporting these. Keep 'em coming.

**Comment by cmstead** [comment]
Just a heads up, I know this has been lingering for a while. I'm trying to come back through and do a bug sweep. Watch for new versions in the next month or two.

**Comment by cmstead** [comment]
Trailing semicolon issue resolved in upcoming release. Package available for side load:

https://github.com/cmstead/js-refactor/releases/download/v2.15.3/jsrefactor-2.15.3.vsix

**Comment by cmstead** [comment]
Side note on some of the comments regarding style:

The indentation is based on a VS Code setting, so if there are indentation issues, it's worth reviewing your settings. Unfortunately, I can't control that. : (

As far as single parameter arrow functions still having parentheses, I had to make a judgement call since some people prefer the parentheses and some don't.  I opted for parentheses in the case the parameter list needed to be expanded. Either choice I made would make someone unhappy.

**Comment by cmstead** [comment]
After poking at the #4 issue, it looks like you are missing an escape slash in your regex, which makes the expression unparseable. I have a separate issue open to bubble up parse errors when Esprima fails to parse the code.

The expression should be:

s.replace(/[-\/\\^$*+?.()|[\]{}]/g, '\\$&');

**Comment by cmstead** [comment]
The last of the issues listed here are complete and in the latest version of JSR.

https://github.com/cmstead/js-refactor/releases/tag/v2.15.6
