### ISSUE TITLE
Non of the available methods are being executed.

### ISSUE THREAD

**Issue by milodude** [cmstead/js-refactor#78]
- Extension Name: jsrefactor
- Extension Version: 2.15.1
- OS Version: Windows_NT x64 10.0.17134
- VSCode version: 1.28.1

 We have written the needed data into your clipboard. Please paste:```json 
{
	"activationTimes": {
		"startup": false,
		"codeLoadingTime": 3,
		"activateCallTime": 39,
		"activateResolvedTime": 0,
		"activationEvent": "onCommand:cmstead.jsRefactor.extractVariable"
	}
}
```

I have this stackoverflow question were you have more details. [Link](https://stackoverflow.com/questions/52786989/how-to-enable-js-refactor-in-visual-studio-code)

**Comment by cmstead** [comment]
Hi, could you provide an example of the code that extract variable won't work for? There are cases that have been popping up which fail and I've been trying to address them as they are found.

**Comment by milodude** [comment]
Yes,

` test("Empty field validation", (){
    var result = FieldValidations.validateEmptyField("", 'validation is null');
    expect(result, 'validation is null');
  });`

I just wanted to take out the string "validation is null" out to be used in two places.

**Comment by cmstead** [comment]
That doesn't look like valid Javascript. The function keyword, or an arrow, is missing, which means the parser is probably failing.

**Comment by cmstead** [comment]
I'm going to use this bug report as impetus to try and surface when Esprima fails to parse the source code.  I think the real bug here is lack of communication when something deeper is breaking which could help the developer identify issues in the code they are working with.

**Comment by cmstead** [comment]
I acctually created a new issue, so I'm closing this one:

https://github.com/cmstead/js-refactor/issues/85
