### ISSUE TITLE
inline variable is broken

### ISSUE THREAD

**Issue by Vegita2** [cmstead/js-refactor#79]
Trying to inline the variable `g` breaks the code

```
var g = 2 + 2;
var b = {
    test: g,
    g: [2,3]
};
```
 after inline variable g
```
var b = {
    test: 2 + 2,
    2 + 2: [2, 3]
};
```

**Comment by cmstead** [comment]
I've seen this before. I'll use your example to write a test around it and fix it. Thanks for the heads up!

**Comment by cmstead** [comment]
I know this has been sitting for a while. I have been working on trying to get another component folded into the tool for some time now, but I need to get back to this.

Anyway, there is a deeper issue in the way I am doing some of the identifier capture logic, which I think I might have an approach to fix.  I'm digging into it at the moment and it will help fix, not only this issue, but other related oddities as well.  Thanks so much for your patience as I run around like a crazy person trying to patch things up and enhance the tool.

**Comment by cmstead** [comment]
I've identified and fixed this bug. Will be in the next release.

**Comment by cmstead** [comment]
Package available for side-load:

https://github.com/cmstead/js-refactor/releases/download/v2.15.3/jsrefactor-2.15.3.vsix
