### ISSUE TITLE
Support Replace Nested Conditional with Guard Clauses

### ISSUE THREAD

**Issue by jagij** [cmstead/js-refactor#82]
Check https://refactoring.guru/replace-nested-conditional-with-guard-clauses

Problem:
```
if (someCondition) {
	return sendMessage(stuff);
} else {
	return Promise.reject('not supported');
}
```

In real code, the 'sendMessage' call is probably a nested structure of similar checks.

If we want to migrate towards the happy path should be on the same line structure (see https://medium.com/@matryer/line-of-sight-in-code-186dd7cdea88 for instance), we'd want to move all the return or throw statements in those else legs into a guard clause. Like this:

```
if (!someCondition) {
	return Promise.reject('not supported');
}
return sendMessage(stuff);
```

**Comment by cmstead** [comment]
I'd be open to help on this if anyone is interested.

**Comment by cmstead** [comment]
There doesn't seem to be enough interest to garner conversation. I'm assuming this is similar enough it can be resolved with an invert conditional. Closing.
