### ISSUE TITLE
Unable to parse source code. Parser error: Line 12: Unexpected token ...

### ISSUE THREAD

**Issue by darrinholst** [cmstead/js-refactor#86]
Can't parse file when using an object spread operator. I saw a mention of babel in #54. Is that still a possibility? Would be great to be able to use this with "babel valid" code. Thanks for the work on this.

**Comment by cmstead** [comment]
I'll take a look at the version of Esprima I'm using. Rest and spread should parse okay, they are part of the standard as of 2015, and object initializer syntax was added last year.

My work on switching to Babel halted when I discovered the tooling wasn't robust enough for what I need. I'm currently working on adding Typescript support, which should also cover the standard, plus extra.

**Comment by cmstead** [comment]
I switched from Esprima to its successor Espree.  This should make a difference in the outcome you're seeing.

https://github.com/cmstead/js-refactor/releases/tag/v2.18.2

(Latest version has been published to the marketplace, but it takes a little bit to go through)

**Comment by darrinholst** [comment]
🎉 working now. Thanks!
