### ISSUE TITLE
Parameterless functions don't convert to arrow functions properly

### ISSUE THREAD

**Issue by cmstead** [cmstead/js-refactor#87]
Parameterless functions don't work.

For example: 
```javascript
const listener = server.listen(8080, function() {
  console.log('Your app is listening on port ' + listener.address().port);
})
```
Doesn't become this:
```javascript
const listener = server.listen(8080,() => {
  console.log('Your app is listening on port ' + listener.address().port);
})
```

**Comment by cmstead** [comment]
Tested manually with example code and could not reproduce.

**Comment by alexilyaev** [comment]
@cmstead Tested with 

Given the original code:

```js
const listener = server.listen(8080, function() {
  console.log("Your app is listening on port " + listener.address().port);
});
```

1. Selecting the function (or cursor on it)
2. Run JS Refactor: Convert To Arrow Function

Result:

```js
const listener = server.listen(8080, () =>
  console.log("Your app is listening on port " + listener.address().port)
);
```

### Issues:

1. Missing function body with curly braces, right now it returns the result of the console.log expression, which is not the same as having no `return` in the body
2. Missing semicolon at the end of the console.log line

### Notes

1. I have Prettier extension, disabling it gives the following result (which again is not the same behavior):

```js
const listener = server.listen(8080, () => console.log("Your app is listening on port " + listener.address().port));
```

2. If the function body is multi-line, the refactor works as expected, although has bad indent for the first line:

```js
const listener = server.listen(8080, () => {
console.log("Your app is listening on port " + listener.address().port);
  console.log("Your app is listening on port " + listener.address().port);
});
```

**Comment by cmstead** [comment]
Thanks for the clarification. I will reopen and take a look at what I can do to improve this behavior.
