### ISSUE TITLE
Failed to install: ENAMETOOLONG

### ISSUE THREAD

**Issue by matanhershberg** [cmstead/js-refactor#90]
I am getting this error when trying to install the plugin.

`[sharedprocess] [error] Failed to install extension: cmstead.jsrefactor ENAMETOOLONG: name too long, open '/home/matan/.vscode/extensions/.cmstead.jsrefactor-2.18.2/node_modules/dject/test/approvals/DJect.Register_and_manage_modules.Build_Module.instantiable_modules.constructs_a_dependency_tree_with_an_instantiable_object_in_the_middle.approved.txt'`

VS Code version:
Version: 1.34.0
Commit: a622c65b2c713c890fcf4fbf07cf34049d5fe758
Date: 2019-05-15T21:55:35.507Z
Electron: 3.1.8
Chrome: 66.0.3359.181
Node.js: 10.2.0
V8: 6.6.346.32
OS: Linux x64 5.0.0-15-generic snap

**Comment by cmstead** [comment]
Sorry I overlooked this for so long.  I didn't realize it was being deployed with the test files. (They are excluded from the build.)

I'll take a look at it.

**Comment by cmstead** [comment]
This should be resolved. If it reappears, let's reopen. Thanks.

**Comment by payton109** [comment]
I'm getting the same ENAMETOOLONG error (about the same file) when trying to install.
ENAMETOOLONG: name too long, open '~/.vscode/extensions/.cmstead.jsrefactor-2.20.5/node_modules/dject/test/approvals/DJect.Register_and_manage_modules.Build_Module.instantiable_modules.constructs_a_dependency_tree_with_an_instantiable_object_in_the_middle.approved.txt'

VS Code:
Version: 1.40.1
Commit: 8795a9889db74563ddd43eb0a897a2384129a619
Date: 2019-11-13T16:49:30.162Z
Electron: 6.1.2
Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron.0
OS: Linux x64 5.3.0-23-generic

**Comment by awvalenti** [comment]
Same here:

ENAMETOOLONG: name too long, open '/home/andre/.vscode/extensions/.cmstead.jsrefactor-2.20.5/node_modules/dject/test/approvals/DJect.Register_and_manage_modules.Build_Module.instantiable_modules.constructs_a_dependency_tree_with_an_instantiable_object_in_the_middle.approved.txt'

Versão: Commit de 1.41.1: 26076a4de974ead31f97692a0d32f90d735645c0 Data: 2019-12-18T15:04:31.999Z elétron: 6.1.5 Chrome: 76.0.3809.146 node. js: 12.4.0 V8: 7.6.303.31-electron.0 OS: Linux x64 4.15.0-50-generic

**Comment by azatoth** [comment]
Same here:

```
[2020-01-14 10:08:55.043] [renderer1] [error] ENAMETOOLONG: name too long, open '/home/carl/.vscode/extensions/.cmstead.jsrefactor-2.20.5/node_modules/dject/test/approvals/DJect.Register_and_manage_modules.Build_Module.instantiable_modules.constructs_a_dependency_tree_with_an_instantiable_object_in_the_middle.approved.txt': extracting: ENAMETOOLONG: name too long, open '/home/carl/.vscode/extensions/.cmstead.jsrefactor-2.20.5/node_modules/dject/test/approvals/DJect.Register_and_manage_modules.Build_Module.instantiable_modules.constructs_a_dependency_tree_with_an_instantiable_object_in_the_middle.approved.txt'
    at file:///usr/share/code/resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:418:559
```

**Comment by squigglybob** [comment]
VS code: 
Version: 1.41.1
Commit: 26076a4de974ead31f97692a0d32f90d735645c0
Date: 2019-12-18T15:04:31.999Z
Electron: 6.1.5
Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron.0
OS: Linux x64 4.15.0-74-generic snap

Same here: ENAMETOOLONG: name too long, open '/home/nath/.vscode/extensions/.cmstead.jsrefactor-2.20.5/node_modules/dject/test/approvals/DJect.Register_and_manage_modules.Build_Module.instantiable_modules.constructs_a_dependency_tree_with_an_instantiable_object_in_the_middle.approved.txt'
