### ISSUE TITLE
Extension page links to wrong website

### ISSUE THREAD

**Issue by alirezaghey** [cmstead/js-refactor#91]
The [extension's](https://marketplace.visualstudio.com/items?itemName=cmstead.jsrefactor) page on marketplace.visualstudion.com links to a dubious website (chrisstead.com) which appears to have nothing to do with the author's website (http://www.chrisstead.net).

**Comment by cmstead** [comment]
Oh, good catch! My site changed and I missed the link here. Thank you!

**Comment by alirezaghey** [comment]
I made a pull request, correcting the address in readme.md and overview.md.
Hope that helps.

**Comment by cmstead** [comment]
I'll approve it in the morning. Thank you!

**Comment by alirezaghey** [comment]
Hey @cmstead,
I don't want to nag you on this, but thought you may have forgotten about it.
Cheers!

**Comment by cmstead** [comment]
It's in. Thank you again.
