### ISSUE TITLE
feat: transform ternary expression to if / else condition statement

### ISSUE THREAD

**Issue by legend80s** [cmstead/js-refactor#93]
Could we have the feature of transforming ternary expression to if / else condition statement?

```javascript
value ? subscribe() : unsubscribe();
```
==>
```javascript
if (value) {
  subscribe();
} else {
  unsubscribe();
}
```

**Comment by cmstead** [comment]
It seems doable.  I am concerned about the example case you gave, since ternaries are expressions and return values, so the functionality isn't exactly one-to-one.

**Comment by cmstead** [comment]
I have migrated this over the the replacement project JS CodeFormer. This is currently the only item in the issues list, so it will be the next behavior delivered.

New issue:

https://github.com/cmstead/js-codeformer/issues/17

**Comment by cmstead** [comment]
This is now available in the latest release of JS CodeFormer:

https://github.com/cmstead/js-codeformer/releases/tag/v1.11.0
