### ISSUE TITLE
Support for flow

### ISSUE THREAD

**Issue by baob** [cmstead/js-refactor#95]
https://flow.org/

Presently, js-refactor doesn't seem to accept the syntax of js with flow annotations.

**Comment by cmstead** [comment]
I'll see what I can do.  This may take some time before you see any movement. Sorry in advance.

**Comment by cmstead** [comment]
I think I might have a solution. I'm going to have to run some experiments, but there seems to be tooling to support this.

**Comment by cmstead** [comment]
This has been sitting for a long time, and it looks like community support and tooling are starting to suffer. Unfortunately, I am going to need to close this.
