### ISSUE TITLE
Stabilize and reintroduce Extract Method for react files

### ISSUE THREAD

**Issue by cmstead** [cmstead/js-refactor#96]
Extract method works as expected except when extracting a JSX element, then everything goes sideways. I am looking into this particular issue and will introduce extract method once it is stable.

If there is a general outcry that unstable is better than nothing, I will enable it and consider it a known issue until the time when I can resolve it.

**Comment by machineghost** [comment]
Would love to see this fixed.

**Comment by cmstead** [comment]
In the theme of SO SO SO late...

JSR is no longer supported because I created a ground-up replacement for it -- JS CodeFormer. This bug is fixed in the new package, which is available now:

GitHub (bugfix):

https://github.com/cmstead/js-codeformer/releases/tag/v0.13.6

VS Marketplace:

https://marketplace.visualstudio.com/items?itemName=cmstead.js-codeformer
