### ISSUE TITLE
Typescript casts are incorrectly flagged as JSX tags

### ISSUE THREAD

**Issue by adamscura-spinplay** [cmstead/js-refactor#97]
JS Refactor is causing typescript cast expressions in angle brackets to be identified as JSX tags. This causes errors all the way to the end of the file because it expects a closing tag.

![image](https://user-images.githubusercontent.com/48136340/64996729-9b5f0a80-d893-11e9-9c95-c258250427ee.png)

**Comment by cmstead** [comment]
Great find, thank you! I'll look into that shortly.

**Comment by cmstead** [comment]
This should be in the latest release (2.20.3).

Sorry for the issue. Please reopen if you discover it isn't resolved.

Thanks!
