### ISSUE TITLE
Request: Positional parameters -> Options object

### ISSUE THREAD

**Issue by edbrannin** [cmstead/js-refactor#99]
I'd like a refactor option to convert some or all of a function's parameters to properties on an options object.

Before:

```javascript
const myFunction = (a, b, c, d, e, f = 0) => a + b + c + d + e + f

console.log(myFunction(1, 2, c, d, e))
```

After:
```javascript
const myFunction = ({ a, b, c, d, e, f = 0 }) => a + b + c + d + e + f

console.log(myFunction({ a: 1, b: 2, c: 3, d: 4, e: 5 }))
```

**Comment by cmstead** [comment]
That's interesting. I can definitely do each part independently. It'll take some work to get everything working together. External files will likely not get support, but I hope a first couple iterations will walk us closer to a usable solution.

**Comment by cmstead** [comment]
I am migrating this issue to the replacement project called JS CodeFormer. I did a quick and dirty migration with a link back to your original issue. This is one of three enhancements on my short list, so you can expect to see this soon. For reference to the new issue, please see the following link:

https://github.com/cmstead/js-codeformer/issues/16

**Comment by cmstead** [comment]
The parameter portion of this request is complete: Toggle function parameter declaration type

This allows the developer to toggle between positional parameters and destructured parameters.

The new feature is available in the latest JS CodeFormer release:

https://github.com/cmstead/js-codeformer/releases/tag/v1.3.0

**Comment by cmstead** [comment]
The function call arguments portion of this is now complete. I will be closing this issue in JS CodeFormer. Cheers!

https://github.com/cmstead/js-codeformer/releases/tag/v1.6.1
